version: "3.9"

services:
  database:
    container_name: ecommerce_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
