spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    password: test
    username: test
stacktrace:
  trace: true
stripe:
  api:
    key: ${STRIPE_KEY}
application:
  base:
    url: http://localhost:8080/api/v1/
