spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  devtools:
    livereload:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  error:
    include-exception: false
    include-stacktrace: on_param
    include-message: always
    include-binding-errors: always
stacktrace:
  trace: false

