name: Only Tests


on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  run-all-tests:
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Set up environment variables
        run: |
          echo "STRIPE_KEY=${{ env.STRIPE_KEY }}" >> $GITHUB_ENV

      - name: All the tests and coverage checks
        run: mvn clean install
