name: Only Tests

on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  run-all-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 3.8.7

      - name: All the tests and coverage checks
        run: mvn clean install
